### ISSUE TITLE
Update mock-fcc-data following the new schema

### ISSUE THREAD

**Issue by Qianru69** [freeCodeCamp/classroom#319]
**Describe the bug**
Currently, the mock-fcc-data is following an old schema, which only contains students' completion from one certificate. Now we want to update the data schema to a new version (https://gist.github.com/GuillermoFloresV/7dbe1abada7babc69b626d47b8e23247), which contains students' completion from multiple certificates. 

**Additional context**
Need to generate an updated mock-fcc-data
Need to modify the components/dashtable_v2.js file to access the modified data

**Comment by ngillux** [comment]
Gonna work on this issue.

**Comment by ngillux** [comment]
I wanted to make a note, as well as clarify that since the json-server node module is being used, would the new payload have to be formatted the way in which the json-server module expects, i.e., each key exposed directly at the root of the JSON object, would be the 'endpoint' name needed to get the data?

Example:

1. Current Mock Data 'fccdata.json' (correct formatting)
{
    "data": [
        "email": {
             etc ... 
        }
    ]
}

So when the url 'https://3001(etc)/data' is entered, the information held in the "data" key is served: "email" and etc.

2. New payload (needs to be formatted, and please correct me if I'm wrong) 
[
  {
    "email": "someemail@email.com",
    "certifications": 
    etc ...
    }
]

This should be an object, and within it have some key like "data" which is an array of objects (in order to correctly use the json-serve module), this is my assumption.


From my understanding, and from what I've tested, adding a "data" key at the top level of the json object, and changing it to an object will correctly serve the data.

Example:

{
  "data": [
  {
    "email": "someemail@email.com",
    "certifications": 
    etc ...
    }
   ]
}

And then going to the url 'https://3001(etc)/data'  would serve the object: "email", "certifications" etc.

I just wanted to point this out / clarify this because the new sample payload (url below) doesn't some to match the formatting, and I changed it to the above formatting in order for it to work, but is that incorrect to do?

https://gist.github.com/GuillermoFloresV/7dbe1abada7babc69b626d47b8e23247

**Comment by lloydchang** [comment]
@Code-Victor 👆
